# Resources/config/services.yaml

services:
  # The service id must be the controller fully-qualified class name.
  # If it a snake case string like `vendor_foo.controller.entry_category`,
  # then an alias must be created.
  # Vendor\FooBundle\Controller\EntryCategoryController:
  #     alias: '@vendor_foo.controller.entry_category'
  #     public: false

    WebMasta\MarkdownTest\Controllers\MarkdownController:
    # Setting class is redundant, but adds autocompletions for the IDE.
    class: WebMasta\MarkdownTest\Controllers\MarkdownController
    arguments:
    # Add this tag to inject services into controller actions.
    tags: ['controller.service_arguments']
    # Call the setContainer method to get access to the services via
    # $this->get() method.
    calls:
      - ['setContainer', ['@service_container']]